/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gestionecole;

import org.junit.Test;

// import com.gestionecole.App;

// import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appCanBeInstantiated() {
        App classUnderTest = new App();
        // Ici, on vérifie simplement que l'instance se crée sans erreur
        assert classUnderTest != null;
    }
}
